spring:
  profiles:
    active: ${RUNTIME_ENV:local}
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: test
    password: test
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8000

api:
  title: Demo Rewards Service
  description: Provides total points earned by a customer within a given date range
  terms-url: https://www.spectrum.com/policies/terms-of-service
  license:
    name: Demo License
    url: https://www.spectrum.com
  version: 1.0.0